name: automation-intents
on:
  workflow_dispatch:
    inputs:
      intent:
        description: 'Intent JSON generado por n8n'
        required: true
      draft:
        description: 'Abrir PR como draft'
        required: false
        default: 'true'

jobs:
  apply-intent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Save intent to repo
        run: |
          mkdir -p automation/intents
          printf '%s' "${{ inputs.intent }}" > "automation/intents/intent-${{ github.run_id }}-$(date +%Y%m%d%H%M%S).json"

      - name: Apply intent changes
        env:
          INTENT_JSON: ${{ inputs.intent }}
        run: node scripts/automation/apply-intent.mjs

      - name: Format (optional)
        run: |
          npx prisma format || true
          npx prettier -w . || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: automation/intent-${{ github.run_id }}
          draft: ${{ inputs.draft }}
          commit-message: "chore: apply intent ${{ github.run_id }} — ${{ fromJSON(inputs.intent).title || 'auto' }}"
          title: "${{ fromJSON(inputs.intent).title || 'Automation: apply intent' }}"
          body: |
            🤖 **PR Automático generado por n8n**

            **Título:** ${{ fromJSON(inputs.intent).title }}
            **Requerimiento:** ${{ fromJSON(inputs.intent).requirement }}

            **Cambios:**
            ${{ fromJSON(inputs.intent).changes }}

            **Archivos modificados:**
            ${{ toJSON(fromJSON(inputs.intent).files) }}

            **Intent (JSON):**
            ```json
            ${{ toJSON(fromJSON(inputs.intent)) }}
            ```
